using Xunit;

namespace AutoInterface.Tests;

public static class NamespaceAndUsingsTests {
    [Fact]
    public static void NestedNamespace() {
        const string input = $$"""
            using AutoInterfaceAttributes;

            namespace MyCode {
                namespace Nested {
                    [AutoInterface]
                    public class Test {
                        public void SomeMethod() { }
                    }
                }
            }

            """;
        string sourceText = input.GenerateSourceText(out _, out _)[^1];

        string expected = $$"""
            {{Shared.GENERATED_SOURCE_HEAD}}

            namespace MyCode.Nested;

            public partial interface ITest {
                void SomeMethod();
            }

            """;
        Assert.Equal(expected, sourceText);
    }

    [Fact]
    public static void NestedUsings() {
        const string input = $$"""
            using AutoInterfaceAttributes;

            namespace MyCode {
                using A;
                namespace Nested {
                    using nested.A;

                    [AutoInterface]
                    public class Test {
                        public void SomeMethod() { }
                    }
                }
            }

            """;
        string sourceText = input.GenerateSourceText(out _, out _)[^1];

        string expected = $$"""
            // <auto-generated/>
            #pragma warning disable
            #nullable enable annotations


            using nested.A;
            using A;
            using AutoInterfaceAttributes;

            namespace MyCode.Nested;

            public partial interface ITest {
                void SomeMethod();
            }

            """;
        Assert.Equal(expected, sourceText);
    }
}
