namespace AutoInterface;

public static partial class Attributes {
    public const string IgnoreAutoInterfaceAttribute = """
    // <auto-generated>
    #pragma warning disable
    #nullable enable annotations


    namespace AutoInterfaceAttributes;

    /// <summary>
    /// The decorated member will be Ignored by the generator.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Method | AttributeTargets.Event)]
    internal sealed class IgnoreAutoInterfaceAttribute : Attribute { }

    """;
}
