using AssemblyVersionInfo;

namespace AutoInterface;

public static partial class Attributes {
    public const string AutoInterfaceVisibilityProtectedInternalAttribute = $$"""
        // <auto-generated/>
        #pragma warning disable
        #nullable enable annotations


        #if !AUTOINTERFACE_EXCLUDE_ATTRIBUTES

        using System;

        namespace AutoInterfaceAttributes;

        /// <summary>
        /// Adds a "protected internal" access modifier to the interface member.
        /// </summary>
        [AttributeUsage(AttributeTargets.Property | AttributeTargets.Method | AttributeTargets.Event)]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("{{Assembly.NAME}}", "{{Assembly.VERSION_MAJOR_MINOR_BUILD}}")]
        internal sealed class AutoInterfaceVisibilityProtectedInternal : Attribute { }

        #endif

        """;
}
